Replace IF STATEMENT with predicate expression (pt. I)
  /cc @tmornini @brandondees @btakita #YAGNI 😎

  The Struggle still persists. #NoIfStatements seems to work in bash as
  well.

  P.S. DO remember...Bash docs state If statements USE predicates.
  However a predicate is not an if statement. #FreeJewelry
  I believe the same goes for ALL languages that have conditions.

diff --git a/bin/snuggsi b/bin/snuggsi
--- a/bin/snuggsi
+++ b/bin/snuggsi
@@ -32,13 +32,12 @@ function run {
   local \
     executable=$1
 
-  if test ${executable##*/} == snuggsi \
-  || test ! -f $executable
-    then
-      echo "🔴  Invalid command \`${executable##*/}\`"
-      ${executable%\/*}/help
-      exit 1
-  fi
+  test ! -f $executable \
+    || test ${executable##*/} == snuggsi \
+    && echo "🔴  Invalid command \`${executable##*/}\`" \
+    && ${executable%\/*}/help \
+    && exit 1
+
 
   echo "📚  MOUNTING RESOURCES …"
   printf '    📁  %s\n' "${resources[@]}"
